### ISSUE TITLE
[Feature] Triggering dbt Exposure

### ISSUE THREAD

**Issue by wornjs** [astronomer/astronomer-cosmos#1142]
### Description

Purpose
The tables created by dbt are used by external systems (e.g., Tableau). These external systems usually fetch dbt tables at specific times as they are unaware when the dbt job is completed. It would be better if Cosmos could trigger these exposures.

```
version: 2
exposures:
  - name: weekly_jaffle_metrics
    label: Jaffles by the Week
    type: dashboard
    maturity: high
    url: https://bi.tool/dashboards/1
    description: >
      Did someone say "exponential growth"?
      
    depends_on:
      - ref('fct_orders')
    owner:
      name: Callum McData
      email: data@jaffleshop.com

    # this 
    meta:
      project: task class
      task parameter      
 ```     

### Create Airflow Task Interface:
Develop a generic interface for Airflow tasks.
Ensure it includes hooks for user customization.
### User Overrides:
Document the process for users to override the default task.
Provide examples and templates for common use cases.

### Are you willing to submit a PR?

- [X] Yes, I am willing to submit a PR!
