### ISSUE TITLE
[Bug] Not able to use clickhouse profile

### ISSUE THREAD

**Issue by petershenri** [astronomer/astronomer-cosmos#1249]
### Astronomer Cosmos Version

main (development)

### If "Other Astronomer Cosmos version" selected, which one?

1.7.0

### dbt-core version

1.8.7

### Versions of dbt adapters

dbt-adapters==1.7.0
dbt-clickhouse==1.8.2
dbt-common==1.10.0
dbt-core==1.8.7
dbt-extractor==0.5.1
dbt-semantic-interfaces==0.5.1

### LoadMode

AUTOMATIC

### ExecutionMode

DOCKER

### InvocationMode

None

### airflow version

2.9.2

### Operating System

MACOS

### Deployment

Docker-Compose

### What happened?

Hello,

When I try to connect to clickhouse with astronomer, I've got the error : `DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.`

If I go to : 
`cosmos/profiles/clickhouse/user_pass.py
`
I can see : 
```
    required_fields = [
        "host",
        "login",
        "schema",
        "clickhouse",
    ]
    secret_fields = [
        "password",
    ]
    airflow_param_mapping = {
        "host": "host",
        "login": "login",
        "password": "password",
        "port": "port",
        "schema": "schema",
        "clickhouse": "extra.clickhouse",
    }
```

Shouldn't it be with user instead ? 
```
    required_fields = [
        "host",
        "user",
        "password",
        "dbname",
    ]
    secret_fields = [
        "password",
    ]
    airflow_param_mapping = {
        "host": "host",
        "user": "login",
        "password": "password",
        "port": "port",
        "dbname": "schema",
        "keepalives_idle": "extra.keepalives_idle",
        "sslmode": "extra.sslmode",
    }
```

My working configuration on DBT is : 
````
project:
  outputs:
    stage:
      type: clickhouse
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      #optional fields
      driver: native
      port: 9440
      host: myhost
      secure: true
      cluster: "all-replicated"
  target: stage
  ````

My unworking configuration on airflow : 
![image](https://github.com/user-attachments/assets/f09cae52-c9ca-44ad-a968-23fca211e990)
````
profile_config = ProfileConfig(
    profile_name="project",
    target_name="stage",
    profile_mapping=ClickhouseUserPasswordProfileMapping(
        conn_id=f"clickhouse_{CONN_ENV}",
        profile_args={
            "cluster": "all-replicated",
            "secure": True,
        },
    ),
)
````

Thanks a lot,

### How to reproduce

Launching airflow on docker and try to connect to clickhouse

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
