### ISSUE TITLE
Dataset only emit for specific models

### ISSUE THREAD

**Issue by DanMawdsleyBA** [astronomer/astronomer-cosmos#1442]
### Description

We're looking into leveraging datasets but one problem we're having is the ability to control which models produce datasets. Would it be possible to implement something to be able to control which models produce datasets. Perhaps using a list or regex of models to emit datasets?

### Use case/motivation

As part of dbt we use a lot of working tables were we don't want to emit datasets and want to cut down on the number of datasets as the airflow graph can get hard to use. 

### Are you willing to submit a PR?

- [ ] Yes, I am willing to submit a PR!

**Comment by tatiana** [comment]
@DanMawdsleyBA I haven't tried this, but it may be possible with Cosmos 1.8., thanks to @wornjs' #1339 contribution:
https://astronomer.github.io/astronomer-cosmos/getting_started/custom-airflow-properties.html

You could try to  set `RenderConfig(emit_datasets=False)` at a `DbtDag` or `DbtTaskGroup` level, and in the models you wanted to emit datasets, you could try to configure:

```
version: 2

models:
  - name: name
    description: description
    meta:
      owner: 'jaegwon.seo@toss.im'
      cosmos:
        operator_kwargs:
          emit_datasets: True
```

Since this parameter is set at an operator level:
https://github.com/astronomer/astronomer-cosmos/blob/184e45fc23044e52fa2033f4f546ebfd4ab2c249/cosmos/operators/base.py#L34

Could you please try it and let us know how it goes?
