### ISSUE TITLE
[feature] Support using different callback methods and arguments per dbt node in `DbtDag` and `DbtTaskGroup`

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#1515]
Cosmos 1.8  (PR #1339) introduced the capability of different tasks running with different configurations when using `DbtDag` and `DbtTaskGroup`. During the same release, there were significant improvements regarding callback support.

Users can currently define the callback when instantiating an operator:

```
    seed_operator = DbtSeedLocalOperator(
        profile_config=profile_config,
        project_dir=DBT_PROJ_DIR,
        task_id="seed",
        dbt_cmd_flags=["--select", "raw_customers"],
        install_deps=True,
        append_env=True,
        callback=upload_to_aws_s3,
        callback_args={"aws_conn_id": "aws_s3_conn", "bucket_name": "cosmos-artifacts-upload"},
)
```

And users can define a callback for the whole `DbtDag` or `DbtTaskGroup`:

```
cosmos_callback_dag = DbtDag( 
     # dbt/cosmos-specific parameters 
     project_config=ProjectConfig( 
         DBT_ROOT_PATH / "jaffle_shop", 
     ), 
     profile_config=profile_config, 
     operator_args={ 
         "install_deps": True,  # install any necessary dependencies before running any dbt command 
         "full_refresh": True,  # used only in dbt commands that support this flag 
         "callback": upload_to_gcp_gs, 
         "callback_args": {"gcp_conn_id": "gcp_gs_conn", "bucket_name": "cosmos-artifacts-upload"}, 
     }, 
```

However, users cannot leverage #1339 to define different callback methods that should be used with specific dbt nodes, using something like:

```
version: 2

models:
  - name: model-with-custom-callback
    description: description
    meta:
      cosmos:
        operator_kwargs:
          callback: "cosmos.io.upload_to_gcp_gs"
          callback_args:
            gcp_conn_id: "gcp_gs_conn"
            bucket_name: "cosmos-artifacts-upload"
```

The goal of this feature is to support this use-case.

**Comment by tatiana** [comment]
This feature was requested in #airflow-dbt by Aldo
> My code is old (like >2years) and I remember the support with Athena adapter in that moment was not done, that’s why I developed a custom taskgroup builder, now surely I would use Cosmos :smile:. Reading the docs seems that callback feature is very useful for the use case I presented and I am curious about if it is possible to implement callback at ‘dbt command’ and/or dbt model level by taking the callables from yml files (where the models are defined) instead of defining each command/task as an Operator?

https://apache-airflow.slack.com/archives/C059CC42E9W/p1738876086358599?thread_ts=1736957747.855309&cid=C059CC42E9W

**Comment by jroach-astronomer** [comment]
> However, users cannot leverage https://github.com/astronomer/astronomer-cosmos/pull/1339 to define different callback methods that should be used with specific dbt nodes, using something like:

```
version: 2

models:
  - name: model-with-custom-callback
    description: description
    meta:
      cosmos:
        operator_kwargs:
          callback: "cosmos.io.upload_to_gcp_gs"
          callback_args:
            gcp_conn_id: "gcp_gs_conn"
            bucket_name: "cosmos-artifacts-upload"
```

@tatiana, regarding the above, is this due to how #1339 was written, or is there another reason that this is not supported?
