### ISSUE TITLE
[Bug] Detached tests from schema not running correctly

### ISSUE THREAD

**Issue by anyapriya** [astronomer/astronomer-cosmos#1679]
### Astronomer Cosmos Version

1.9.2

### dbt-core version

1.8.4

### Versions of dbt adapters

dbt-bigquery==1.8.2

### LoadMode

DBT_LS

### ExecutionMode

LOCAL

### InvocationMode

DBT_RUNNER

### airflow version

2.10.5

### Operating System

Debian GNU/Linux 12

### Deployment

Astronomer

### What happened?

When "test_behavior=TestBehavior.AFTER_EACH" and "should_detach_multiple_parents_tests=True", then tests pulled from schema are run with a ".{id}" appended to them, which means that dbt can't find the test and thus runs nothing.  Logs in the relevant log output below, notice there's a ".f3f13d987e" appended.  

This is correctly excluded in the single-model tests though, with no ".{id}" appended.  
```
[2025-04-18, 13:12:27 UTC] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['--no-partial-parse', 'test', '--exclude', 'relationships_model_2__id___id__ref_model_1_', '--models', 'model_2', '--project-dir', '/tmp/tmpg_wedf7j', '--profiles-dir', '/tmp/cosmos/profile/f32680d1e89957914305232740ca4b180b377263fd4b22b144b6dcdea2e2a424', '--profile', 'mini_test', '--target', 'local']
```

### Relevant log output

```shell
[2025-04-18, 13:12:33 UTC] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['--no-partial-parse', 'test', '--select', 'relationships_model_2__id___id__ref_model_1_.f3f13d987e', '--project-dir', '/tmp/tmp_9w2e9r2', '--profiles-dir', '/tmp/cosmos/profile/f32680d1e89957914305232740ca4b180b377263fd4b22b144b6dcdea2e2a424', '--profile', 'mini_test', '--target', 'local']
 in /tmp/tmp_9w2e9r2
[2025-04-18, 13:12:34 UTC] {logging_mixin.py:190} INFO - 13:12:34  Running with dbt=1.8.4
[2025-04-18, 13:12:34 UTC] {logging_mixin.py:190} INFO - 13:12:34  Registered adapter: bigquery=1.8.2
[2025-04-18, 13:12:36 UTC] {logging_mixin.py:190} INFO - 13:12:36  Found 2 models, 5 data tests, 484 macros
[2025-04-18, 13:12:36 UTC] {logging_mixin.py:190} INFO - 13:12:36  The selection criterion 'relationships_model_2__id___id__ref_model_1_.f3f13d987e' does not match any enabled nodes
[2025-04-18, 13:12:36 UTC] {logging_mixin.py:190} INFO - 13:12:36
[2025-04-18, 13:12:36 UTC] {logging_mixin.py:190} INFO - 13:12:36  Nothing to do. Try checking your model configs and model specification args
```

### How to reproduce

model_1.sql
```
SELECT 1 AS _id
```

model_2.sql
```
SELECT 
    _id
FROM {{ ref('model_1') }}
```

schema.yml
```
version: 2

models:

  - name: model_1
    columns:
      - name: _id
        data_tests:
          - unique
          - not_null

  - name: model_2
    columns:
      - name: _id
        data_tests:
          - unique
          - not_null
          - relationships:
              to: ref('model_1')
              field: _id
```

Render config:
```
render_config = RenderConfig(
    emit_datasets=False,
    test_behavior=TestBehavior.AFTER_EACH, 
    should_detach_multiple_parents_tests=True,
    load_method=LoadMode.DBT_LS,
)
```

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!
