### ISSUE TITLE
[Feature] Allow building dags instead of dynamic parsing

### ISSUE THREAD

**Issue by 1cadumagalhaes** [astronomer/astronomer-cosmos#1780]
### Description

Hey there!
Not sure if this is better to do as an issue or discussion, we can move if you guys find it better.

I am currently building a dag parser, similar to dag-factory, but I am merging python and yaml files, and I went into trying to actually generate static dag files to not depend too much in the dag processor, and to be able to take advantage of dag versioning.

So what if cosmos could actually build the dag based on the dbt project, instead of dynamic generation. I know many of the optimizations made come from trying to make this faster, but building dags + a ci/cd process would allow us to take more control over the resources used. 

So this would make cosmos be not one operator that generates things dynamically, but a tool. 

Any thoughts? Would this be in the interest of the project?
Of course I can just create a new package and take some inspiration of what is already done by cosmos. Or even create a package that creates the interface to do this, not sure. 

### Use case/motivation

Enhance performance, better integration with dag bundles and dag versioniong.

### Are you willing to submit a PR?

- [x] Yes, I am willing to submit a PR!

**Comment by 1cadumagalhaes** [comment]
Also, if anyone is interested in my parser idea, I am still testing and finishing it, but the idea for me is that a dag should be written of two files: a python file for code, and a yaml file for configuration. So I write the dag as a normal dag, but use my decorator instead of the default taskflow api.

So I can do something like this:
<details>
<summary>my_dag.py</summary>
<p>

```py
from airflow.operators.bash import BashOperator
from airflow.operators.empty import EmptyOperator

from dag_parser.core.decorator import dag_generator


@dag_generator()
def transfer_example_decorator_dag(dag, environment, **kwargs):

    start = EmptyOperator(task_id='start', dag=dag)
    extract = BashOperator(
        task_id='extract',
        bash_command=f"echo 'Extracting data in {environment} with decorator'",
        dag=dag,
    )
  
    end = EmptyOperator(task_id='end', dag=dag)
    start >> extract  >> end
    return [end]

```
</p>
</details> 

<details><summary>my_dag.yaml</summary>
<p>

```yaml
dag_display_name: Transfer Example Decorator
dag_id: transfer_example_decorator
schedule: "@daily"
owner: data_engineering
fail_fast: true
tags:
  - transfer
  - decorator_example

documentation: |
  # Transfer Example Decorator DAG

outlets:
  - transfer_example_decorator_data

notification:
  enabled: true
  on_failure: true
  on_success: false
```

</p>
</details>
