### ISSUE TITLE
select & exclude configs are not working as expected 

### ISSUE THREAD

**Issue by saswatkumarsahoo** [astronomer/astronomer-cosmos#190]
I am using select property in the DbtDag. I was assuming models tagged with **daily** should only be rendered in the task group.
However the DAG does not render anything i.e. empty DAG with no tasks.  Similarly with exclude tag, all the models are appearing in the DAG including the tagged model with exclusion value.  
```
from cosmos.providers.dbt import DbtDag

    my_dag = DbtDag(
        # ...
        select={"configs": ['tag:daily']},
    )
```

config file: schema.yml

version: 2

```
models:
  - name: table_1
    description: "A starter dbt model"
    config:
      tags: ['daily']
```
