### ISSUE TITLE
Update dbt select/exclude documentation

### ISSUE THREAD

**Issue by MikeWallis42** [astronomer/astronomer-cosmos#203]
This [section](https://github.com/astronomer/astronomer-cosmos/blob/main/docs/dbt/configuration.rst?plain=1#L32-L35) suggests that you should structure your select or exclude like this.

```python3
select={"configs": "tags:daily"}
```
This too did not work but at least did not result in no tasks being returned.
```python3
select={"tags": "daily"}
```
I'm setting my tags in dbt_project.yml, not schema.yml or directly inside the models like below.
Is this supported?
```yaml
models:
  jaffle_shop:
      staging:
        +tags:
          - hourly
      modelling:
        +tags:
          - daily
      mart:
        +tags:
          - daily
```
