### ISSUE TITLE
Add support dbt project render for models contract

### ISSUE THREAD

**Issue by jensenity** [astronomer/astronomer-cosmos#260]
Starting from dbt 1.5.0, models now supports both model contract and model version.
https://docs.getdbt.com/docs/collaborate/govern/model-contracts.

we can define just the model name with the version argument separately. 

```
models:
  - name: dim_customers
    latest_version: 1
    config:
      materialized: table
      contract: {enforced: true}
    columns:
      - name: customer_id
        description: This is the primary key
        data_type: int
      - name: country_name
        description: Where this customer lives
        data_type: varchar
    
    # Declare the versions, and highlight the diffs
    versions:
    
      - v: 1
        # Matches what's above -- nothing more needed
    
      - v: 2
        # Removed a column -- this is the breaking change!
        columns:
          # This means: use the 'columns' list from above, but exclude country_name
          - include: all
            exclude: [country_name]
```
https://docs.getdbt.com/docs/collaborate/govern/model-versions

But the rendering doesn't not fully support the versions in config yaml so there are some minor logic need to add in the DbtProject class while handling sql files and config files.
