### ISSUE TITLE
bind=False doesn't apply when dbt run using Airlfow. 

### ISSUE THREAD

**Issue by ayudovin** [astronomer/astronomer-cosmos#327]
Hello, I execute the following model for my redshift to create the view:
```
{{
  config(
    materialized='view',
    schema='public',
    bind=False
  )
}}

with source as (

    select * from {{ source('test', 'test_users') }} limit 10

),

renamed as (

    select
        id as customer_id,
        email,
        country

    from source

)

select * from renamed
```

dbt_project.yml:

```
name: 'redshift_unload'

config-version: 2

profile: 'redshift_unload'
version: '1.0.0'

model-paths: ["models"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  +bind: false
  redshift_unload:
      materialized: view

```

and got the following exception:
```
External tables are not supported in views
HINT:  Please use late binding view and add 'with no schema binding' at the query end.
```
I use dbt in the Airflow:
```
dbt_tg = DbtTaskGroup(
    dbt_project_name="redshift_unload",
    dbt_root_path=f"/usr/local/airflow/dbt/",
    conn_id="redshift_dbt",
    dbt_args={
        "schema": "sandbox_zone",
        "dbt_executable_path": "/usr/local/airflow/dbt_venv/bin/dbt",
    },
)
```

- I tried on different versions but one of them: 

```
dbt-core==1.4.5
dbt-postgres==1.4.5
dbt-redshift==1.4.0
```
- bind=False is the [configuration](https://docs.getdbt.com/reference/resource-configs/redshift-configs#late-binding-views) that has been specially created by dbt for Redshift. 
- The most important part is that when I execute `dbt run --model <model>` without without Apache Airflow, everything works fine.
