### ISSUE TITLE
GoogleCloudServiceAccountDictProfileMapping should create yaml fields

### ISSUE THREAD

**Issue by joppedh** [astronomer/astronomer-cosmos#443]
The `GoogleCloudServiceAccountDictProfileMapping` should extend the fields as yaml and not as JSON as it does now. This is not supported by DBT. See https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#service-account-json

Currently it creates the profile like so:
```yaml
bigquery:
    outputs:
        dev:
            dataset: my_bigquery_dataset
            keyfile_json: '{   "type": "service_account",   "project_id": "stg",   "universe_domain":
                "googleapis.com" }'
            method: service-account-json
            threads: 1
            type: bigquery
```
It should be like so:
```yaml
bigquery:
    outputs:
        dev:
            dataset: my_bigquery_dataset
            keyfile_json: 
              type: xxx
              project_id: xxx
              private_key_id: xxx
            method: service-account-json
            threads: 1
            type: bigquery
```
