### ISSUE TITLE
Allow use of enviroment variables in profiles when using profiles_yml_filepath

### ISSUE THREAD

**Issue by DanMawdsleyBA** [astronomer/astronomer-cosmos#468]
I'm looking to build a dag which uses environment variables in the profiles when using a yml path. Something like the below:

```
dbt_envs= {
    'user': 'test',
    'private_key': <lookup private key>
}

profile_config = ProfileConfig(
    profile_name='dbt_project',
    target_name='snowflake_dev',
    profiles_yml_filepath='/usr/local/airflow/dags/dbt/profiles.yml',
    env=dbt_envs
)
```

With the profile yml referencing it like:
```
    snowflake_dev:
      type: snowflake
      account: test_account.eu-west-1
      user: "{{ env_var('USER') }}"
      private_key: "{{ env_var('PRIVATE_KEY') }}"
```

**Comment by tatiana** [comment]
Hi @DanMawdsleyBA, Thanks for your message!

Some questions:
1) Which `execution_mode` are you using?
2) Are you setting the environment variables `USER` and `PRIVATE_KEY` when running Airflow, or would the expectation be that Cosmos should set them at a process level?

If the environment variables are available for the Airflow process, a way to forward them to the underlining Cosmos/Airflow operators is to use:
```
`operator_args={"append_env": True}`
```

**Comment by DanMawdsleyBA** [comment]
Thanks for your response so I would be looking to build a dbt dag that would run all models and tests so running `dbt build`
So in the python dag I have lookup the aws secret using `service_client.get_secret_value(SecretId='secret_value')` this retrieves all the connection details. 

So if set the operator_args as above could I do something like this:
in the dag have:
```
user='user'
private_key=service_client.get_secret_value(SecretId='secret_value')

my_cosmos_dag = DbtDag(
    project_config=ProjectConfig(dbt_project_path='/usr/local/airflow/dags/oprn_crw_ops_planning/dbt'),
    profile_config=profile_config,
    operator_args={"append_env": True},
    # normal dag parameters
    schedule_interval='@daily',
    start_date=datetime(2023, 1, 1),
    catchup=False,
    dag_id=f'{Path(__file__).stem}_{env}',
)
```
in the profile have the below and it would be populated with the value user and private key from the dag:
```
    snowflake_dev:
      type: snowflake
      account: test_account.eu-west-1
      user: "{{ env_var('USER') }}"
      private_key: "{{ env_var('PRIVATE_KEY') }}"
```
Is that correct?
