### ISSUE TITLE
Mock values unable to be parsed by dbt

### ISSUE THREAD

**Issue by joppevos** [astronomer/astronomer-cosmos#586]
When parsing the cosmos DAG in CI/CD, I am running into issues with dbt.

```
Runtime Error
  Credentials in profile "default", target "prod" invalid: 'mock_value' is not valid under any of the given schemas
```
I am using the following profile mapping.
`GoogleCloudServiceAccountDictProfileMapping`

The mock profile it creates:
```yaml
 default:
    outputs:
        prod:
            dataset: mock_value
            keyfile_json: mock_value
            method: service-account-json
            project: project
            threads: 1
            type: bigquery
    target: prod 
```

The key `keyfile_json: mock_value` in the above yaml is not accepted by DBT
For the mock we can simply remove the field. 

## Reproduce
Take above mock profile and put it in a `profiles.yml`
run `dbt ls`

or 

```python
from pathlib import Path

from cosmos import DbtDag, ProfileConfig, ProjectConfig
from cosmos.profiles import GoogleCloudServiceAccountDictProfileMapping
from pendulum import datetime


CURRENT_DIR = Path(__file__).resolve().parent

profile_config = ProfileConfig(
    profile_name="profile",
    target_name="target",
    profile_mapping=GoogleCloudServiceAccountDictProfileMapping(
        conn_id="conn", profile_args={}
    ),
)
my_cosmos_dag = DbtDag(
    dag_id="dag",
    start_date=datetime(2023, 1, 1),
    schedule_interval="@daily",
    project_config=ProjectConfig(
        dbt_project_path=CURRENT_DIR,
    ),
    profile_config=profile_config,
    catchup=False,
)

```

Running with dbt=1.5.6
Comos 1.1.2
