### ISSUE TITLE
Model-level tests ignored when using Custom load method

### ISSUE THREAD

**Issue by gbatiz** [astronomer/astronomer-cosmos#594]
Cosmos version:

1.1.3

Cosmos config:

```python

    dbt = DbtTaskGroup(
        project_config=ProjectConfig(
            dbt_project_path=DBT_CONFIG['path_project_folder'],
        ),
        profile_config=ProfileConfig(
            profile_name=DBT_CONFIG['profile_name'],
            target_name=os.environ['AWS_ENV'],
            profiles_yml_filepath=DBT_CONFIG['path_profiles_folder'] + "profiles.yml",
        ),
        execution_config=ExecutionConfig(
            dbt_executable_path=DBT_CONFIG["path_dbt_venv_folder"] + "bin/dbt",
        ),
        render_config=RenderConfig(
            load_method=LoadMode.CUSTOM,
            emit_datasets=False,
        ),
        operator_args=dict(
            append_env=True,
            env=ENV,
            dbt_cmd_global_flags=[
                "--no-use-colors",
            ],
            on_failure_callback=slack_fail.handle_callback,
        ),
        on_warning_callback=slack_warn.handle_callback,
    )
```

dbt model:

```yml
version: 2
models:

- name: stg_events_kafka_prod_via_s3_contracts
  config:
    alias: contracts
    schema: staging_events_kafka_prod_via_s3
    elementary:
      timestamp_column: _META_LOADED_AT
  tests:
    - elementary.freshness_anomalies:
        # https://docs.elementary-data.com/guides/elementary-tests-configuration
        # where_expression: ""
        severity: warn
        anomaly_sensitivity: 0.001
        backfill_days: 1
        days_back: 28
        anomaly_direction: both
        time_bucket:
          period: day
          count: 1
        seasonality: day_of_week
        min_training_set_size: 14
```

The testing Airflow task only gets created if I add a column-level test as well, such as 

```yml
  columns:
    - name: contract_id
      datatype: "NUMBER(38,0)"
      # description:
      tests:
        - not_null
```

# Excepted outcome

Test task created for even if only model-level tests are defined.
