### ISSUE TITLE
Support dbt selector arg for manifest and custom load modes

### ISSUE THREAD

**Issue by jbandoro** [astronomer/astronomer-cosmos#767]
This is a follow up to #718 for which support for using selector was added in #755 for dbt ls load mode. It would be great if we could add support for the selector when using `LodeMode.DBT_MANIFEST` and `LoadMode.CUSTOM`.

Adding support for manifest/custom will involve first parsing the [YAML selectors](https://docs.getdbt.com/reference/node-selection/yaml-selectors) which can have 3 types of `definition` for the selector:

1. cli-style:
    ```yaml
    definition:
      'tag:nightly'
    ```
2. key-value:
    ```yaml
    definition:
      tag: nightly
    ```
3. full yaml with [method selection](https://docs.getdbt.com/reference/node-selection/methods):
    ```yaml
    definition:
      method: tag
      value: nightly

      # Optional keywords map to the `+` and `@` graph operators:

      children: true | false
      parents: true | false

      children_depth: 1    # if children: true, degrees to include
      parents_depth: 1     # if parents: true, degrees to include

      childrens_parents: true | false     # @ operator

      indirect_selection: eager | cautious | buildable | empty # include all tests selected indirectly? eager by default
    ```

The selector can also have `union`, `intersection` and `exclude` like in the example below:
```yaml
selectors:
  - name: nightly_diet_snowplow
    description: "Non-incremental Snowplow models that power nightly exports"
    definition:
      # Optional `union` and `intersection` keywords map to the ` ` and `,` set operators:
      union:
        - intersection:
            - method: source
              value: snowplow
              childrens_parents: true
            - method: tag
              value: nightly
        - method: path
          value: models/export
        - exclude:
            - intersection:
                - method: package
                  value: snowplow
                - method: config.materialized
                  value: incremental
            - method: fqn
              value: export_performance_timing
```

Further more there can be [selector inheritance](https://docs.getdbt.com/reference/node-selection/yaml-selectors#selector-inheritance)where one selector can reference another one. 

The full yaml parsing will be the most challenging, but this is the reason why selectors are often used over `--select` and `--exclude` for complex selections.

One possible solution is to add a new method to `GraphSelector` which can parse the full YAML selector, there is a method currently for [parsing REGEX strings](https://github.com/astronomer/astronomer-cosmos/blob/9fcee8e785ea3bcb0d19e8d36f3f5b94bedafc98/cosmos/dbt/selector.py#L77-L87).
