### ISSUE TITLE
[Bug]  Invalid aws session token

### ISSUE THREAD

**Issue by ssulca** [astronomer/astronomer-cosmos#962]
Cosmos in AthenaAccessKeyProfileMapping always tries to use a session token, even when it is not provided by the Airflow connection

**Context**

* astronomer-cosmos= "1.3.2"
* dbt-core = "1.7.14"
* dbt-athena-community = "1.7.2"

When setting up a new aws connection using only `aws_access_key_id` and `aws_secret_access_key`, it
generates a profile like this:

```yaml
profile_name:
    outputs:
        athena:
            aws_access_key_id: KEY_ID
            aws_secret_access_key: '{{ env_var(''COSMOS_CONN_AWS_AWS_SECRET_ACCESS_KEY'')}}'
            aws_session_token: '{{ env_var(''COSMOS_CONN_AWS_AWS_SESSION_TOKEN'')}}'
            database: db_name
            ...
    target: athena
```
But  `AthenaAccessKeyProfileMapping` sets the `aws_session_token` as an empty string, and dbt takes this value,
resulting in. 

```sh
'botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException)
 when calling the GetDatabases operation: 
The security token included in the request is invalid', ''
```

**Propose solutions**
In [profile](https://github.com/astronomer/astronomer-cosmos/blob/e4aa3c48d8f9206c416dd94aba73ad3d4e6b391f/cosmos/profiles/athena/access_key.py#L59C1-L60C1) function

Add a condition that check if there is a token.
```python
profile = {
    **self.mapped_params,
    **self.profile_args,
    "aws_access_key_id": self.temporary_credentials.access_key,
    "aws_secret_access_key": self.get_env_var_format("aws_secret_access_key"),
    "aws_session_token": self.get_env_var_format("aws_session_token") if self.temporary_credentials.token else None,
}
```
