### ISSUE TITLE
AthenaAccessKeyProfileMapping does not work as expected locally

### ISSUE THREAD

**Issue by tuan-h** [astronomer/astronomer-cosmos#996]
When defining an AWS connection like so in `airflow_settings.yaml`:
```yaml
airflow:
  connections:
    - conn_id: aws_default
      conn_type: aws
      conn_host:
      conn_schema:
      conn_login: {aws_access_key_id}
      conn_password: {aws_secret_access_key} 
      conn_port:
      conn_extra:
```

Running a dag with [`AthenaAccessKeyProfileMapping`](https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/profiles/athena/access_key.py) returns this error:

`botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid`

And that's because `AwsGenericHook` returns [`frozen_credentials`](https://github.com/apache/airflow/blob/1734b15e4efb124d9a37591e22c208529241e50a/airflow/providers/amazon/aws/hooks/base_aws.py#L774) as defined above, i.e. **no session token**, when calling [`get_credentials`](https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/profiles/athena/access_key.py#L99) in `AthenaAccessKeyProfileMapping`.

To make the dag run successfully, I have to use AWS CLI `aws sts get-session-token` and then define the connection like this:
```yaml
airflow:
  connections:
    - conn_id: aws_default
      conn_type: aws
      conn_host:
      conn_schema:
      conn_login: {session_access_key_id}
      conn_password: {session_secret_access_key} 
      conn_port:
      conn_extra:
        aws_session_token: {session_token)
```

However, this is annoying to do every time a session expire. To fix this issue, I subclassed `AthenaAccessKeyProfileMapping` to make the call to `sts` in code:
```python
from typing import Any

from cosmos.profiles import (
    AthenaAccessKeyProfileMapping as BaseAthenaAccessKeyProfileMapping,
)


class AthenaAccessKeyProfileMapping(BaseAthenaAccessKeyProfileMapping):
    @property
    def profile(self) -> dict[str, Any | None]:
        "Gets profile. The password is stored in an environment variable."

        self.temporary_credentials = self._get_temporary_credentials()  # type: ignore

        profile = {
            **self.mapped_params,
            **self.profile_args,
            "aws_access_key_id": self.temporary_credentials["Credentials"]["AccessKeyId"], # from sts
            "aws_secret_access_key": self.get_env_var_format("aws_secret_access_key"),
            "aws_session_token": self.get_env_var_format("aws_session_token"),
        }

        return self.filter_null(profile)

    @property
    def env_vars(self) -> dict[str, str]:
        "Overwrites the env_vars for athena, Returns a dictionary of environment variables that should be set based on the self.temporary_credentials."

        if self.temporary_credentials is None:
            raise CosmosValueError(f"Could not find the athena credentials.")

        env_vars = {}

        env_secret_key_name = self.get_env_var_name("aws_secret_access_key")
        env_session_token_name = self.get_env_var_name("aws_session_token")

        env_vars[env_secret_key_name] = str(
            self.temporary_credentials["Credentials"]["SecretAccessKey"] # from sts
        )
        env_vars[env_session_token_name] = str(
            self.temporary_credentials["Credentials"]["SessionToken"] # from sts
        )

        return env_vars

    def _get_temporary_credentials(self):  # type: ignore
        """
        Helper function to retrieve temporary short lived credentials
        Returns an object including access_key, secret_key and token
        """
        # use StsHook to get session
        from airflow.providers.amazon.aws.hooks.sts import StsHook

        hook = StsHook(self.conn_id)  # type: ignore
        duration = self.profile_args.get("duration_seconds", 3600)
        credentials = hook.conn.get_session_token(DurationSeconds=duration)
        return credentials

```

I'm not sure if this is the best solution. Additionally, I don't think this will work with a deployed Airflow that runs with an IAM role that already has a session. That is, it will fail to call `get_session_token` due to [session limitation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sts/client/get_session_token.html):

>  The temporary security credentials created by GetSessionToken can be used to make API calls to any Amazon Web Services service with the following exceptions: You cannot call any STS API except AssumeRole or GetCallerIdentity
